// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzvXUTmVhQwAEAefUTY3iAw9sLWWaEWeg',
    appId: '1:565733212138:web:e20e9ccfc645261ec23c93',
    messagingSenderId: '565733212138',
    projectId: 'course-a0d02',
    authDomain: 'course-a0d02.firebaseapp.com',
    storageBucket: 'course-a0d02.firebasestorage.app',
    measurementId: 'G-D2VMQW8JXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRl2tVddBOBgLG5EYFoXlSrE0hYuspRlo',
    appId: '1:565733212138:android:84dd7c677b0344a4c23c93',
    messagingSenderId: '565733212138',
    projectId: 'course-a0d02',
    storageBucket: 'course-a0d02.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD62zPthix1sEOOLHb4B6R1rszkatvSBuI',
    appId: '1:565733212138:ios:1afd8158ea150638c23c93',
    messagingSenderId: '565733212138',
    projectId: 'course-a0d02',
    storageBucket: 'course-a0d02.firebasestorage.app',
    iosBundleId: 'com.example.flutterSamples',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD62zPthix1sEOOLHb4B6R1rszkatvSBuI',
    appId: '1:565733212138:ios:1afd8158ea150638c23c93',
    messagingSenderId: '565733212138',
    projectId: 'course-a0d02',
    storageBucket: 'course-a0d02.firebasestorage.app',
    iosBundleId: 'com.example.flutterSamples',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzvXUTmVhQwAEAefUTY3iAw9sLWWaEWeg',
    appId: '1:565733212138:web:0a519f6d9f1e909bc23c93',
    messagingSenderId: '565733212138',
    projectId: 'course-a0d02',
    authDomain: 'course-a0d02.firebaseapp.com',
    storageBucket: 'course-a0d02.firebasestorage.app',
    measurementId: 'G-EJQVDDX3QV',
  );
}
